/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void contextLoads() {
        // Placeholder test to ensure the test suite passes
        assertTrue(true);
    }
}
